# This file was auto generated by Valama 0.1.2. Do not modify it.
set(project_name "yatla")
set(yatla_VERSION "0.1.0")
set(required_pkgs
  "gee-0.8"
  "gio-2.0"
  "glib-2.0"
  "gobject-2.0"
  "granite"
  "gtk+-3.0"
  "libnotify"
  "sqlheavy-0.1"
)
set(srcfiles
  "src/Yatla.vala"
  "src/Database.vala"
  "src/DateTime.vala"
  "src/Layout.vala"
  "src/Task.vala"
  "src/Widgets/Preferences.vala"
  "src/Widgets/Sidebar.vala"
  "src/Widgets/TaskPreferences.vala"
  "src/Widgets/Toolbar.vala"
)
set(vapifiles
  "vapi/config.vapi"
)